
# Back-end Service 
apiVersion: v1
kind: Service
metadata:
  # can't add "-service" at end because "-" is not allowed in here 
  name: be
  labels:
    app.kubernetes.io/part-of: be-monitor
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: be-deployment
  ports:
  # front needs to be connected via ingress (or any public address) as the backend needs to be public in order to work with react application. 
  # Reason: React tries to make BE requests via browser meaning user should be able to access the backend publically
  - port: 8080
    targetPort: 8080
  type: ClusterIP # making it private as now using Ingress Controller
