apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest # no 14.9 image on dockerhub
          env:
            - name: POSTGRES_USER
              value: "USERNAME" # replace me using secrets
            - name: POSTGRES_PASSWORD
              value: "PASSWORD" # replace me using secrets
            - name: POSTGRES_DB
              value: "appdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # postgres default path for storing db
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc