

# ingress for FE & BE
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ig
spec:
  rules:
  - http:
      paths:
      # front end
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fe
            port:
              number: 3000
      # back end
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: be
            port:
              number: 8080
  ingressClassName: nginx